<a href="https://colab.research.google.com/github/AadityaAdh/Sparse_tensors/blob/main/Sparse_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


Sparse tensors are a type of data structure used in various machine learning and numerical computing applications to efficiently represent and store tensors that have a large number of zero or near-zero elements. In contrast to dense tensors, which store every element, sparse tensors only store the non-zero elements along with their indices.

This can be beneficial in scenarios where the data is sparse, meaning that a significant portion of the tensor consists of zeros. Sparse tensors help save memory and computational resources, as operations involving zero elements are avoided.

so ysma cai non zero ko value matrai save hunxa
aani tini haru kun kun index ma xan tyo pani
aani original zero huda ko matrix shape matrai not matrix
aani yesko yo shape lae yedi zero ni vako tensor banuni ho vanae banauna sakinxa

#tf.sparse.SparseTensor


Represents a sparse tensor.

tf.sparse.SparseTensor(


    indices, values, dense_shape
)

indices vanya kun kun index ma non zero xan
values vanya non zero values
dense shape vanya original shape zero pani huda ko

indices:

	A 2-D int64 tensor of shape [N, ndims].
values:

	A 1-D tensor of any type and shape [N].
dense_shape:

	A 1-D int64 tensor of shape [ndims].

In [ ]:
x=tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
x

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [ ]:
#0,0 ma vako value 1 vanya aani 1,2 ma vako value chai 2 vanya
#aaba yesko original matrix herni vaye


#tf.sparse.to_dense(your sparse tensor)
to convert it to like zero pani vako tensor ma



In [ ]:
tf.sparse.to_dense(x)
#dense_shape 3,4 xa so 3,4 ko matrix
#aani jun jun index ma value dya xa tyo value
#baki rako ma zer0

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [ ]:
#lets do it for 3d
k=tf.sparse.SparseTensor([[0,0,1],[1,2,1]],[11,22],dense_shape=[2,3,3])
k

SparseTensor(indices=tf.Tensor(
[[0 0 1]
 [1 2 1]], shape=(2, 3), dtype=int64), values=tf.Tensor([11 22], shape=(2,), dtype=int32), dense_shape=tf.Tensor([2 3 3], shape=(3,), dtype=int64))

In [ ]:
tf.sparse.to_dense(k)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 0, 11,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0, 22,  0]]], dtype=int32)>